
/**
 * ⚠️ CRITICAL: YOU MUST REPLACE THE STRING BELOW WITH THE FULL BASE64 OF CAIRO-REGULAR.TTF
 * 
 * Instructions:
 * 1. Go to https://www.giftofspeed.com/base64-encoder/
 * 2. Upload your 'Cairo-Regular.ttf'
 * 3. Copy the resulting Base64 string
 * 4. Paste it inside the backticks below
 */

export const CAIRO_BASE64 = `
AAEAAAALAIAAAwAwT1MvMhVvCZEAAAF8AAAAYGNtYXQbqvFzAAACBAAAAeJjdnQgK68H3QAABTwA
AAAGZ2FzcP//AAMAAAU0AAAACGdseWby/P/lAAAFPAAAB4ZoZWFkF3+KfwAADXAAAAA2aGhlYQd+
B2AAAA2sAAAAJGhtdHjkOA1pAAAN0AAAAERsb2NhBG4ExAAADhQAAAAkbWF4cAAZAEAAAA40AAAA
IG5hbWUxdMzDAAAOVAAAAkRwb3N0/7gAAAARJAAAAAgAAAABAAAAAQAAR7hZ3F8PPPUACwPoAAAA
ANfR8e4AAAAA19Hx7gAA/7wD6QPoAAAACAACAAAAAAAAAAEAAAPo/7wAAAPoAAAAAAPpAAEAAAAA
ABAAAQAAAAEAAAAAAAEAAAAAAA4AAQAAAAAAAAAZAAAAAgAAAAAAAP9/AAACAAIAAAAAAAIAAAAD
AAAAFAADAAEAAAAUAAQAZAAAABAACAACAAQAIQAiACMAJAAlACb//wAAACEAIgAjACQAJQAm////
/94A3QDdANwA2wDaAAD/2wAAAAA=
`; // <-- PASTE FULL BASE64 STRING HERE
