
import React, { useState } from 'react';
import { TeacherProfile, SchoolLevel, AppLanguage } from '../../types';
import {
  User, School, BookOpen, Check, Loader2, Mail, Key, Sun, Moon,
  LogIn, ArrowRight, MapPin, ChevronLeft, ChevronRight,
  Award, Eye, EyeOff, AlertCircle, RotateCcw, Fingerprint, RefreshCcw
} from 'lucide-react';
import { useAuth } from '../../contexts/AuthContext';
import { TamkeenLogo } from '../../components/ui/TamkeenLogo';

interface Props {
  TamkeenLogo: React.FC<any>;
  useBackend?: boolean;
  onRegister?: (profile: TeacherProfile) => void;
  darkMode: boolean;
  setDarkMode: (val: boolean) => void;
  initialUser?: any;
  lang?: AppLanguage;
  setLang?: (lang: AppLanguage) => void;
  onBack?: () => void;
}

const ALGERIA_WILAYAS = [
  "01 - أدرار", "02 - الشلف", "03 - الأغواط", "04 - أم البواقي", "05 - باتنة", "06 - بجاية", "07 - بسكرة", "08 - بشار", "09 - البليدة", "10 - البويرة",
  "11 - تمنراست", "12 - تبسة", "13 - تلمسان", "14 - تيارت", "15 - تيزي وزو", "16 - الجزائر", "17 - الجلفة", "18 - جيجل", "19 - سطيف", "20 - سعيدة",
  "21 - سكيكدة", "22 - سيدي بلعباس", "23 - عنابة", "24 - قالمة", "25 - قسنطينة", "26 - المدية", "27 - مستغانم", "28 - المسيلة", "29 - معسكر", "30 - ورقلة",
  "31 - وهران", "32 - البيض", "33 - إليزي", "34 - برج بوعريريج", "35 - بومرداس", "36 - الطارف", "37 - تندوف", "38 - تيسمسيلت", "39 - الوادي", "40 - خنشلة",
  "41 - سوق أهراس", "42 - تيبازة", "43 - ميلة", "44 - عين الدفلى", "45 - النعامة", "46 - عين تموشنت", "47 - غرداية", "48 - غليزان",
  "49 - تيميمون", "50 - برج باجي مختار", "51 - أولاد جلال", "52 - بني عباس", "53 - إن صالح", "54 - إن قزام", "55 - تقرت", "56 - جانت", "57 - المغير", "58 - المنيعة"
];

export default function RegistrationView({
  TamkeenLogo: PropTamkeenLogo,
  darkMode,
  setDarkMode
}: Props) {
  const auth = useAuth();
  const [isLoginMode, setIsLoginMode] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [registrationStep, setRegistrationStep] = useState(1);
  const [showSuccessModal, setShowSuccessModal] = useState(false);
  const [showPassword, setShowPassword] = useState(false);

  const [formData, setFormData] = useState<any>({
    name: '',
    institution: '',
    level: 'MIDDLE',
    wilaya: '',
    teachingSubject: '',
  });

  const [credentials, setCredentials] = useState({
    email: '',
    password: '',
    confirmPassword: '',
  });

  const handleRegisterSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (registrationStep < 3) { setRegistrationStep(p => p + 1); return; }

    if (credentials.password !== credentials.confirmPassword) {
      setError("كلمات المرور غير متطابقة");
      return;
    }

    if (credentials.password.length < 6) {
      setError("كلمة المرور يجب أن تكون 6 أحرف على الأقل");
      return;
    }

    setError(null);
    setIsSubmitting(true);
    try {
      const profile: TeacherProfile = {
        ...formData,
        tamkeenId: '', // Will be generated by auth service
        email: credentials.email,
        academicYear: '2024/2025',
        province: formData.wilaya,
        preferredShift: 'PARTIAL',
        teachingLanguage: 'ar',
        grades: [],
      };

      await auth.register(credentials.email, credentials.password, profile);
      setShowSuccessModal(true);
    } catch (err: any) {
      console.error("Registration error:", err);
      setError(err.message || "فشل التسجيل.");
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleLoginSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setIsSubmitting(true);
    try {
      await auth.login(credentials.email, credentials.password);
    } catch (err: any) {
      setError(err.message || "بيانات الدخول غير صحيحة أو الحساب غير موجود.");
    } finally {
      setIsSubmitting(false);
    }
  };

  const Logo = PropTamkeenLogo || TamkeenLogo;

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900 flex items-center justify-center p-4 font-['Cairo'] transition-colors duration-300" dir="rtl">
      <div className="bg-white dark:bg-slate-800 w-full max-w-2xl rounded-[2.5rem] shadow-2xl overflow-hidden relative border border-slate-100 dark:border-slate-700 animate-in fade-in duration-500">
        <div className="p-8 md:p-12">
          <div className="flex flex-col items-center mb-8">
            <Logo size={50} className="mb-4" />
            <h2 className="text-2xl font-black text-slate-800 dark:text-white">
              {isLoginMode ? 'تسجيل الدخول' : `إنشاء حساب (${registrationStep}/3)`}
            </h2>
            <p className="text-xs text-slate-400 mt-2 font-bold">نسخة سطح المكتب - يعمل بدون إنترنت</p>
          </div>

          {error && (
            <div className="p-4 rounded-2xl text-center font-bold mb-6 text-sm flex flex-col items-center gap-2 bg-rose-50 dark:bg-rose-900/20 text-rose-500 border border-rose-100 dark:border-rose-900/30 animate-shake">
              <div className="flex items-center gap-2"><AlertCircle size={18} /><span>{error}</span></div>
            </div>
          )}

          {isLoginMode ? (
            <form onSubmit={handleLoginSubmit} className="space-y-6">
              <div className="space-y-4">
                <div className="relative">
                  <Mail className="absolute right-4 top-3.5 text-slate-400" size={20} />
                  <input type="email" required placeholder="البريد الإلكتروني" className="w-full bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-2xl py-3.5 pr-12 pl-4 outline-none text-slate-900 dark:text-white" value={credentials.email} onChange={e => setCredentials({ ...credentials, email: e.target.value })} />
                </div>
                <div className="relative">
                  <Key className="absolute right-4 top-3.5 text-slate-400" size={20} />
                  <input type={showPassword ? "text" : "password"} required placeholder="كلمة المرور" className="w-full bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-2xl py-3.5 pr-12 pl-12 outline-none text-slate-900 dark:text-white" value={credentials.password} onChange={e => setCredentials({ ...credentials, password: e.target.value })} />
                  <button type="button" onClick={() => setShowPassword(!showPassword)} className="absolute left-4 top-3.5 text-slate-400">{showPassword ? <EyeOff size={20} /> : <Eye size={20} />}</button>
                </div>
              </div>
              <button type="submit" disabled={isSubmitting} className="w-full bg-emerald-600 text-white font-black py-4 rounded-2xl shadow-lg hover:bg-emerald-700 transition-all flex items-center justify-center gap-2">
                {isSubmitting ? <Loader2 className="animate-spin" /> : <><span>دخول آمن</span> <LogIn size={20} /></>}
              </button>
              <div className="text-center mt-6">
                <button type="button" onClick={() => setIsLoginMode(false)} className="text-emerald-600 font-bold hover:underline text-sm">ليس لديك حساب؟ سجل الآن</button>
              </div>
            </form>
          ) : (
            <div className="space-y-6">
              {registrationStep === 1 && (
                <div className="space-y-4 animate-in slide-in-from-left-4">
                  <input type="text" placeholder="الاسم واللقب" className="w-full p-3 bg-slate-50 dark:bg-slate-700 border rounded-xl" value={formData.name} onChange={e => setFormData({ ...formData, name: e.target.value })} />
                  <input type="email" placeholder="البريد الإلكتروني" className="w-full p-3 bg-slate-50 dark:bg-slate-700 border rounded-xl" value={credentials.email} onChange={e => setCredentials({ ...credentials, email: e.target.value })} />
                  <input type="password" placeholder="كلمة المرور (6 أحرف على الأقل)" className="w-full p-3 bg-slate-50 dark:bg-slate-700 border rounded-xl" value={credentials.password} onChange={e => setCredentials({ ...credentials, password: e.target.value })} />
                  <input type="password" placeholder="تأكيد كلمة المرور" className="w-full p-3 bg-slate-50 dark:bg-slate-700 border rounded-xl" value={credentials.confirmPassword} onChange={e => setCredentials({ ...credentials, confirmPassword: e.target.value })} />
                </div>
              )}
              {registrationStep === 2 && (
                <div className="space-y-4 animate-in slide-in-from-left-4">
                  <select className="w-full p-3 bg-slate-50 dark:bg-slate-700 border rounded-xl font-bold" value={formData.wilaya} onChange={e => setFormData({ ...formData, wilaya: e.target.value })}>
                    <option value="">اختر الولاية...</option>
                    {ALGERIA_WILAYAS.map(w => <option key={w} value={w}>{w}</option>)}
                  </select>
                  <input type="text" placeholder="المؤسسة التربوية" className="w-full p-3 bg-slate-50 dark:bg-slate-700 border rounded-xl" value={formData.institution} onChange={e => setFormData({ ...formData, institution: e.target.value })} />
                </div>
              )}
              {registrationStep === 3 && (
                <div className="space-y-4 animate-in slide-in-from-left-4">
                  <div className="flex gap-2">
                    {['PRIMARY', 'MIDDLE', 'HIGH'].map(l => (
                      <button key={l} onClick={() => setFormData({ ...formData, level: l as SchoolLevel })} className={`flex-1 p-3 rounded-xl font-bold border transition-all ${formData.level === l ? 'bg-emerald-600 text-white' : 'bg-slate-100 text-slate-500'}`}>{l === 'PRIMARY' ? 'ابتدائي' : l === 'MIDDLE' ? 'متوسط' : 'ثانوي'}</button>
                    ))}
                  </div>
                  <input type="text" placeholder="المادة التعليمية" className="w-full p-3 bg-slate-50 dark:bg-slate-700 border rounded-xl" value={formData.teachingSubject} onChange={e => setFormData({ ...formData, teachingSubject: e.target.value })} />
                </div>
              )}

              <div className="flex gap-3 pt-6 border-t">
                {registrationStep > 1 && <button onClick={() => setRegistrationStep(p => p - 1)} className="p-4 bg-slate-100 rounded-2xl"><ChevronLeft className="rotate-180" /></button>}
                {registrationStep < 3 ? (
                  <button onClick={() => setRegistrationStep(p => p + 1)} className="flex-1 bg-emerald-600 text-white font-black py-4 rounded-2xl">التالي</button>
                ) : (
                  <button onClick={handleRegisterSubmit} disabled={isSubmitting} className="flex-1 bg-emerald-600 text-white font-black py-4 rounded-2xl">{isSubmitting ? <Loader2 className="animate-spin mx-auto" /> : 'تأكيد الحساب'}</button>
                )}
              </div>
              <div className="text-center">
                <button onClick={() => setIsLoginMode(true)} className="text-slate-400 hover:text-emerald-600 text-xs font-bold">العودة لتسجيل الدخول</button>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* --- Success Modal --- */}
      {showSuccessModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-900/90 backdrop-blur-md p-4">
          <div className="bg-white dark:bg-slate-800 w-full max-w-lg rounded-[3rem] p-10 text-center shadow-2xl animate-in zoom-in-95">
            <div className="w-20 h-20 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mx-auto mb-6"><Award size={40} /></div>
            <h2 className="text-2xl font-black text-slate-900 dark:text-white mb-4">تم التسجيل بنجاح!</h2>
            <p className="text-slate-500 mb-6">تم إنشاء حسابك في قاعدة البيانات المحلية</p>
            <button onClick={() => window.location.reload()} className="w-full bg-emerald-600 text-white py-4 rounded-2xl font-black shadow-lg">الدخول للمنصة</button>
          </div>
        </div>
      )}
    </div>
  );
}
